/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Maximum_Peak_Detector_A.h"
#include "Clock_In.h"
#include "Signal_A_aliases.h"
#include "Signal_A.h"
#include "ADC_SAR_A.h"
#include "Signal_B_aliases.h"
#include "Signal_B.h"
#include "Maximum_Peak_Detector_B.h"
#include "ADC_SAR_B.h"
#include "Control_Reg.h"
#include "Comp_A.h"
#include "Comp_B.h"
#include "ISR_START.h"
#include "DMA_A_dma.h"
#include "DMA_B_dma.h"
#include "ISR_A.h"
#include "ISR_B.h"
#include "UART.h"
#include "Pin_2_aliases.h"
#include "Pin_2.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "Counter.h"
#include "Counter_Clock.h"
#include "Maximum_Peak_Detector_A_Sample_Hold.h"
#include "Maximum_Peak_Detector_A_Comp_1.h"
#include "ADC_SAR_A_IRQ.h"
#include "ADC_SAR_A_theACLK.h"
#include "Maximum_Peak_Detector_B_Sample_Hold.h"
#include "Maximum_Peak_Detector_B_Comp_1.h"
#include "ADC_SAR_B_IRQ.h"
#include "ADC_SAR_B_theACLK.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "cy_em_eeprom.h"

/*[]*/

