/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART.h"
#include "DMA_A_dma.h"
#include "ADC_SAR_B.h"
#include "ISR_A.h"
#include "Clock_In.h"
#include "ADC_SAR_A.h"
#include "DMA_B_dma.h"
#include "Sample_Hold_B.h"
#include "Sample_Hold_A.h"
#include "Control_Reg.h"
#include "ISR_B.h"
#include "Comp_A.h"
#include "Comp_B.h"
#include "ISR_START.h"
#include "Clock_1.h"
#include "Status_Reg.h"
#include "UART_IntClock.h"
#include "ADC_SAR_B_IRQ.h"
#include "ADC_SAR_B_theACLK.h"
#include "ADC_SAR_B_Bypass_aliases.h"
#include "ADC_SAR_B_Bypass.h"
#include "ADC_SAR_A_IRQ.h"
#include "ADC_SAR_A_theACLK.h"
#include "ADC_SAR_A_Bypass_aliases.h"
#include "ADC_SAR_A_Bypass.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

