/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Clock_1.h"
#include "ISR_PIN_A.h"
#include "ADC_A.h"
#include "VDAC.h"
#include "Mixer_A.h"
#include "SignalA_aliases.h"
#include "SignalA.h"
#include "Mixer_PD_A.h"
#include "Comp_PD_B.h"
#include "Comp_PD_A.h"
#include "USBUART_1.h"
#include "USBUART_1_audio.h"
#include "USBUART_1_cdc.h"
#include "USBUART_1_hid.h"
#include "USBUART_1_midi.h"
#include "USBUART_1_pvt.h"
#include "USBUART_1_cydmac.h"
#include "USBUART_1_msc.h"
#include "Clock_3.h"
#include "ISR_PIN_B.h"
#include "ADC_B.h"
#include "Mixer_B.h"
#include "SignalB_aliases.h"
#include "SignalB.h"
#include "Counter.h"
#include "Mixer_PD_B.h"
#include "ADC_A_IRQ.h"
#include "ADC_A_theACLK.h"
#include "USBUART_1_Dm_aliases.h"
#include "USBUART_1_Dm.h"
#include "USBUART_1_Dp_aliases.h"
#include "USBUART_1_Dp.h"
#include "ADC_B_IRQ.h"
#include "ADC_B_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

